name: Dynamic Analysis Security Testing
on: 
  push:
    branches:
      - 'main'      
jobs:
  Burp-Dastardly:
    name: Burpsuite Scan
    needs: Build-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Dastardly Action Step
        continue-on-error: true
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'http://103.31.38.112:8081/user/test'
      
      - name: Publish Test Report with JUnit
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/dastardly-report.xml'
          require_tests: true